# Generated by Django 3.1.5 on 2021-01-29 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Please separate full name with space.', max_length=50, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(help_text='Phone number not more than 15 digits', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Address')),
            ],
        ),
    ]
